### ISSUE TITLE
Service call failure repair notification

### ISSUE THREAD

**Issue by benoitb85** [amitfin/retry#58]
## System Information

version | core-2023.11.1
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.4.0-0.deb12.2-amd64
arch | x86_64
timezone | Europe/Paris
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1395
Downloaded Repositories | 5

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 2
views | 12
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | February 13, 2024 at 21:32
-- | --
current_recorder_run | February 18, 2024 at 16:00
estimated_db_size | 723.42 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/amitfin/retry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I'm using the retry integration to turn on and off a switch at night. It seems to work as the switch does turn on and off but I get “repairs” notifications:
## Service call failure
homeassistant.turn_on(entity_id=binary_sensor.salonnord_input) failed after 7 retries. Check the log for additional information.

### Reproduction steps

1. Define an automation with call a service "Retry: Actions" at a fixed time.
2. Define action as Call a service "Home Assistant Core Integration; Generic turn on".
3. Choose a switch device.
4. Wait for the action to trigger when the time arrives.

### Debug logs

```text
2024-02-23 18:10:29.611 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration ble_monitor which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-23 18:10:29.611 ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'ble_monitor' does not have a version key in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
2024-02-23 18:10:29.612 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-23 18:10:29.613 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration retry which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-23 18:10:29.613 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-23 18:10:29.615 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration tapo_control which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-02-23 18:10:38.090 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='10.9.8.200', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb86a43e990>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2024-02-23 18:10:38.118 WARNING (MainThread) [homeassistant.components.generic_thermostat.climate] The climate mode is OFF, but the switch device is ON. Turning off device switch.pilote_parentssud
2024-02-23 18:10:41.169 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='10.9.8.200', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb864ba19d0>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2024-02-23 18:10:54.634 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='10.9.8.200', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb862737650>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2024-02-23 18:11:17.930 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='10.9.8.200', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb863f7ed10>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2024-02-23 18:12:01.098 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='10.9.8.200', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb8627f0f10>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2024-02-23 18:13:00.303 WARNING (MainThread) [homeassistant.components.homeassistant] The service homeassistant.turn_on does not support entities binary_sensor.couloiretage_input
2024-02-23 18:13:00.303 WARNING (MainThread) [custom_components.retry] [Failed]: attempt 1/7: homeassistant.turn_on(entity_id=binary_sensor.couloiretage_input)
Traceback (most recent call last):
  File "/config/custom_components/retry/__init__.py", line 342, in async_retry
    await self._async_validate()
  File "/config/custom_components/retry/__init__.py", line 246, in _async_validate
    raise InvalidStateError(f"{self._entity_id} is not available")
homeassistant.exceptions.InvalidStateError: binary_sensor.couloiretage_input is not available
2024-02-23 18:13:00.344 DEBUG (MainThread) [custom_components.retry] [Succeeded]: attempt 1/7: homeassistant.turn_on(entity_id=switch.couloiretage)
2024-02-23 18:13:01.310 WARNING (MainThread) [homeassistant.components.homeassistant] The service homeassistant.turn_on does not support entities binary_sensor.couloiretage_input
2024-02-23 18:13:01.311 WARNING (MainThread) [custom_components.retry] [Failed]: attempt 2/7: homeassistant.turn_on(entity_id=binary_sensor.couloiretage_input)
Traceback (most recent call last):
  File "/config/custom_components/retry/__init__.py", line 342, in async_retry
    await self._async_validate()
  File "/config/custom_components/retry/__init__.py", line 246, in _async_validate
    raise InvalidStateError(f"{self._entity_id} is not available")
homeassistant.exceptions.InvalidStateError: binary_sensor.couloiretage_input is not available
2024-02-23 18:13:03.315 WARNING (MainThread) [homeassistant.components.homeassistant] The service homeassistant.turn_on does not support entities binary_sensor.couloiretage_input
2024-02-23 18:13:03.316 WARNING (MainThread) [custom_components.retry] [Failed]: attempt 3/7: homeassistant.turn_on(entity_id=binary_sensor.couloiretage_input)
Traceback (most recent call last):
  File "/config/custom_components/retry/__init__.py", line 342, in async_retry
    await self._async_validate()
  File "/config/custom_components/retry/__init__.py", line 246, in _async_validate
    raise InvalidStateError(f"{self._entity_id} is not available")
homeassistant.exceptions.InvalidStateError: binary_sensor.couloiretage_input is not available
2024-02-23 18:13:07.321 WARNING (MainThread) [homeassistant.components.homeassistant] The service homeassistant.turn_on does not support entities binary_sensor.couloiretage_input
2024-02-23 18:13:07.321 WARNING (MainThread) [custom_components.retry] [Failed]: attempt 4/7: homeassistant.turn_on(entity_id=binary_sensor.couloiretage_input)
Traceback (most recent call last):
  File "/config/custom_components/retry/__init__.py", line 342, in async_retry
    await self._async_validate()
  File "/config/custom_components/retry/__init__.py", line 246, in _async_validate
    raise InvalidStateError(f"{self._entity_id} is not available")
homeassistant.exceptions.InvalidStateError: binary_sensor.couloiretage_input is not available
2024-02-23 18:13:15.326 WARNING (MainThread) [homeassistant.components.homeassistant] The service homeassistant.turn_on does not support entities binary_sensor.couloiretage_input
2024-02-23 18:13:15.326 WARNING (MainThread) [custom_components.retry] [Failed]: attempt 5/7: homeassistant.turn_on(entity_id=binary_sensor.couloiretage_input)
Traceback (most recent call last):
  File "/config/custom_components/retry/__init__.py", line 342, in async_retry
    await self._async_validate()
  File "/config/custom_components/retry/__init__.py", line 246, in _async_validate
    raise InvalidStateError(f"{self._entity_id} is not available")
homeassistant.exceptions.InvalidStateError: binary_sensor.couloiretage_input is not available
2024-02-23 18:13:24.362 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='10.9.8.200', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb8626c3950>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
2024-02-23 18:13:31.330 WARNING (MainThread) [homeassistant.components.homeassistant] The service homeassistant.turn_on does not support entities binary_sensor.couloiretage_input
2024-02-23 18:13:31.330 WARNING (MainThread) [custom_components.retry] [Failed]: attempt 6/7: homeassistant.turn_on(entity_id=binary_sensor.couloiretage_input)
Traceback (most recent call last):
  File "/config/custom_components/retry/__init__.py", line 342, in async_retry
    await self._async_validate()
  File "/config/custom_components/retry/__init__.py", line 246, in _async_validate
    raise InvalidStateError(f"{self._entity_id} is not available")
homeassistant.exceptions.InvalidStateError: binary_sensor.couloiretage_input is not available
2024-02-23 18:14:03.336 WARNING (MainThread) [homeassistant.components.homeassistant] The service homeassistant.turn_on does not support entities binary_sensor.couloiretage_input
2024-02-23 18:14:03.336 ERROR (MainThread) [custom_components.retry] [Failed]: attempt 7/7: homeassistant.turn_on(entity_id=binary_sensor.couloiretage_input)
Traceback (most recent call last):
  File "/config/custom_components/retry/__init__.py", line 342, in async_retry
    await self._async_validate()
  File "/config/custom_components/retry/__init__.py", line 246, in _async_validate
    raise InvalidStateError(f"{self._entity_id} is not available")
homeassistant.exceptions.InvalidStateError: binary_sensor.couloiretage_input is not available
2024-02-23 18:14:47.817 ERROR (MainThread) [custom_components.tapo_control] Unable to connect to Tapo: Cameras Control controller: HTTPSConnectionPool(host='10.9.8.200', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb85e882190>: Failed to establish a new connection: [Errno 113] Host is unreachable'))
```

### Diagnostics dump

Couldn't find a download diagnostics link. Should it be on the Retry integration page ?

**Comment by amitfin** [comment]
> `entity_id=binary_sensor.couloiretage_input`

It doesn't seem to be right: `binary_sensor` (and any other type of _sensor_) is a read-only entity. It's not a valid entity for `homeassistant.turn_on`. Valid entities should be from domains like: `light`, `switch`, etc'. See also [`homeassistant.turn_on` documentation](https://www.home-assistant.io/integrations/homeassistant/#service-homeassistantturn_on).

**Comment by benoitb85** [comment]
Thank you ! And sorry for being uneducated about HomeAssistant and creating extra work for you. Using the switch entity only instead of the whole device in the automation editor fixed the problem !
